apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
    - name: ndep
    image: my_nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

    - name: wordpress
    image: wordpress
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data