apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana
        name: grafana
        imagePullPolicy: Never
        livenessProbe:
          initialDelaySeconds: 30
          exec:
           command:
           - sh
           - /health_check.sh
           - grafana-server
           - telegraf
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: grafana
  name: grafana
spec:
  ports:
  - port: 3000
    name: https
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
