---
apiVersion: v1
kind: Service
metadata:
  name: nser
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    -  port: 80
       targetPort: 80
       name: http
    -  port: 443
       targetPort: 443
       name: https
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndep
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my_nginx
        imagePullPolicy: Never
        #command: [ "/bin/sh", "-ce", "nginx && tail -f /dev/null" ]
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.105-192.168.99.120
---