apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  ports:
    - port: 5050
      name: http
      targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http
        command: [ "/bin/sh", "-ce", "/script.sh && tail -f /dev/null" ]
