---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: telegraf
  name: telegraf-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf
        name: telegraf
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/lib/telegraf
          name: var-lib-telegraf
      volumes:
      - name: var-lib-telegraf
        persistentVolumeClaim:
          claimName: telegraf-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: telegraf
  type: ClusterIP
